In [13]:
import os
import sys
lib_path = os.path.join(os.path.dirname('.'), "pybosaris-master")
sys.path.append(lib_path)
lib_path = os.path.join(os.path.dirname('.'), "pybosaris-master/tests")
sys.path.append(lib_path)
from calibration.test_cllrObjective import *

In [14]:
t = TestCllrObjective()

In [16]:
t.setUp()

In [27]:
t.test_BOSARIS()

2019-10-02 11:58:34.101 INFO     test gradient : cstep err = 2.220446049250313e-16, rstep err = 8.098608588608114e-08
2019-10-02 11:58:34.109 INFO     test Jacobian : cstep err = 2.220446049250313e-16, rstep err = 8.098608588608114e-08
2019-10-02 11:58:34.110 INFO     test Jacobian-gradient: 0.0
2019-10-02 11:58:34.111 INFO     test Hess prod: cstep err = 4.163336342344337e-17, rstep err = 1.9195689690554296e-09, cstep-rstep = 1.919568927422066e-09
2019-10-02 11:58:34.113 INFO     test H1-H2: 0.0


In [29]:
import os
import sys
lib_path = os.path.join(os.path.dirname('.'), "pybosaris-master")
sys.path.append(lib_path)
lib_path = os.path.join(os.path.dirname('.'), "pybosaris-master/tests")
sys.path.append(lib_path)
from calibration.test_linearFuser import *

In [30]:
t = TestLinearFuser()

In [31]:
t.test_splitvec_fh()

2019-10-02 12:01:36.596 INFO     test gradient : cstep err = 0.0, rstep err = 0.0
2019-10-02 12:01:36.598 INFO     test Jacobian : cstep err = 0.0, rstep err = 0.0
2019-10-02 12:01:36.599 INFO     test Jacobian-gradient: 0.0
2019-10-02 12:01:36.601 INFO     test Hess prod: cstep err = 0.0, rstep err = 0.0, cstep-rstep = 0.0
2019-10-02 12:01:36.603 INFO     test H1-H2: 0.0
2019-10-02 12:01:36.605 INFO     test gradient : cstep err = 0.0, rstep err = 0.0
2019-10-02 12:01:36.607 INFO     test Jacobian : cstep err = 0.0, rstep err = 0.0
2019-10-02 12:01:36.609 INFO     test Jacobian-gradient: 0.0
2019-10-02 12:01:36.610 INFO     test Hess prod: cstep err = 0.0, rstep err = 0.0, cstep-rstep = 0.0
2019-10-02 12:01:36.611 INFO     test H1-H2: 0.0


In [33]:
t.test_linear_calibration()

2019-10-02 12:06:46.967 INFO     TR 0 (initial state): obj = 1, Delta = 0.214662
2019-10-02 12:06:46.968 INFO     CG 0: curv=0.641345, converged inside trust region; radius = 0.071849, residual=0.954157, model=0.0016554
2019-10-02 12:06:46.969 INFO     TR 1: obj=0.998445; rho=0.939534
2019-10-02 12:06:46.970 INFO     CG 0: curv=0.00793493, radius = 0.0154195, residual=9.24879, model=4.91948e-05
2019-10-02 12:06:46.971 INFO     CG 1: curv=7.254191228292703e-05, terminate on trust region boundary, model=0.001078666639678597
2019-10-02 12:06:46.972 INFO     expanding: Delta=0.429325
2019-10-02 12:06:46.974 INFO     TR 2: obj=0.997364; rho=1.00168
2019-10-02 12:06:46.975 INFO     CG 0: curv=0.00398734, radius = 0.00742055, residual=11.0734, model=3.71673e-05
2019-10-02 12:06:46.976 INFO     CG 1: curv=7.33662E-05, converged inside trust region; radius = 0.822578, residual=1.25468e-13, model=0.00307438
2019-10-02 12:06:46.977 INFO     TR 3: obj=0.994053; rho=1.07693
2019-10-02 12:06:46.979 

In [73]:
def calibrate_get_w(y, s, cstep=False):
    classf = numpy.hstack((numpy.ones(y.sum()), -numpy.ones((1-y).sum())))
    prior = 0.01
    maxiters = 100
    quiet = False
    objfun = None
    scores = numpy.hstack((s[y], s[~y]))
    fuser = LinearFuser(scores=scores)
    w0 = fuser.w
    print(classf)
    print(scores)
    print(w0)
    w, train_cxe, w_pen, optimizerState, converged = train_binary_classifier(
        classifier=fuser, classf=classf, w0=w0,
        objective_function=objfun, prior=prior,
        penalizer=None, penalizer_weight=0,
        maxiters=maxiters, maxCG=100, optimizerState=None, quiet=quiet, cstepHessian=cstep)
    return w

In [74]:
s1 = numpy.arange(len(y1))
s2 = numpy.arange(len(y2))
s3 = numpy.arange(len(y3))
s4 = numpy.arange(len(y4))
y1
y2
y3
y4
s1
s2
s3
s4

w1_matlab = numpy.asarray([0.05690020923651800677, -0.46189701847839187421])
w2_matlab = numpy.asarray([-0.26721010832405112101, 1.48771909454608608492])
w3_matlab = numpy.asarray([0.26720978993204969054, -1.71880034947314586091])
w4_matlab = numpy.asarray([0.10852002944173323729, -1.26878113586522633938])
w1_matlab
w2_matlab
w3_matlab
w4_matlab

w1 = calibrate_get_w(y=y1, s=s1)
w2 = calibrate_get_w(y=y2, s=s2)
w3 = calibrate_get_w(y=y3, s=s3)
w4 = calibrate_get_w(y=y4, s=s4)
w1
w2
w3
w4

assert((numpy.abs(w1 - w1_matlab) < 1e-14).all())
assert((numpy.abs(w2 - w2_matlab) < 1e-14).all())
assert((numpy.abs(w3 - w3_matlab) < 1e-14).all())
assert((numpy.abs(w4 - w4_matlab) < 1e-14).all())

array([False, False,  True, False,  True,  True, False, False,  True,
       False, False,  True, False, False, False,  True,  True])

array([ True, False,  True,  True, False, False,  True, False, False,
        True, False, False, False])

array([False, False, False,  True, False, False,  True, False, False,
        True,  True, False,  True])

array([ True,  True, False, False, False, False,  True, False, False,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True,  True])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([ 0.05690021, -0.46189702])

array([-0.26721011,  1.48771909])

array([ 0.26720979, -1.71880035])

array([ 0.10852003, -1.26878114])

2019-10-02 12:25:49.031 INFO     TR 0 (initial state): obj = 1, Delta = 0.214662
2019-10-02 12:25:49.033 INFO     CG 0: curv=0.641345, converged inside trust region; radius = 0.071849, residual=0.954157, model=0.0016554
2019-10-02 12:25:49.034 INFO     TR 1: obj=0.998445; rho=0.939534
2019-10-02 12:25:49.035 INFO     CG 0: curv=0.00793493, radius = 0.0154195, residual=9.24879, model=4.91948e-05
2019-10-02 12:25:49.037 INFO     CG 1: curv=7.254191228292703e-05, terminate on trust region boundary, model=0.001078666639678597
2019-10-02 12:25:49.039 INFO     expanding: Delta=0.429325
2019-10-02 12:25:49.040 INFO     TR 2: obj=0.997364; rho=1.00168
2019-10-02 12:25:49.042 INFO     CG 0: curv=0.00398734, radius = 0.00742055, residual=11.0734, model=3.71673e-05
2019-10-02 12:25:49.044 INFO     CG 1: curv=7.33662E-05, converged inside trust region; radius = 0.822578, residual=1.25468e-13, model=0.00307438
2019-10-02 12:25:49.045 INFO     TR 3: obj=0.994053; rho=1.07693
2019-10-02 12:25:49.046 

[ 1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 2  4  5  8 11 15 16  0  1  3  6  7  9 10 12 13 14]
[0. 0.]
[ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0  2  3  6  9  1  4  5  7  8 10 11 12]
[0. 0.]
[ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 3  6  9 10 12  0  1  2  4  5  7  8 11]
[0. 0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1.]
[ 0  1  6 10 12 13 14 16 17 18 20 22 23 24  2  3  4  5  7  8  9 11 15 19
 21]
[0. 0.]


array([ 0.05690021, -0.46189702])

array([-0.26721011,  1.48771909])

array([ 0.26720979, -1.71880035])

array([ 0.10852003, -1.26878114])

In [76]:
w1c = calibrate_get_w(y=y1, s=s1, cstep=True)
w2c = calibrate_get_w(y=y2, s=s2, cstep=True)
w3c = calibrate_get_w(y=y3, s=s3, cstep=True)
w4c = calibrate_get_w(y=y4, s=s4, cstep=True)
w1c
w2c
w3c
w4c

assert((numpy.abs(w1c - w1_matlab) < 1e-14).all())
assert((numpy.abs(w2c - w2_matlab) < 1e-14).all())
assert((numpy.abs(w3c - w3_matlab) < 1e-14).all())
assert((numpy.abs(w4c - w4_matlab) < 1e-14).all())

2019-10-02 13:16:40.383 INFO     TR 0 (initial state): obj = 1, Delta = 0.214662
2019-10-02 13:16:40.386 INFO     CG 0: curv=0.641345, converged inside trust region; radius = 0.071849, residual=0.954157, model=0.0016554
2019-10-02 13:16:40.387 INFO     TR 1: obj=0.998445; rho=0.939534
2019-10-02 13:16:40.389 INFO     CG 0: curv=0.00793493, radius = 0.0154195, residual=9.24879, model=4.91948e-05
2019-10-02 13:16:40.391 INFO     CG 1: curv=7.254191228292701e-05, terminate on trust region boundary, model=0.001078666639678597
2019-10-02 13:16:40.391 INFO     expanding: Delta=0.429325
2019-10-02 13:16:40.392 INFO     TR 2: obj=0.997364; rho=1.00168
2019-10-02 13:16:40.393 INFO     CG 0: curv=0.00398734, radius = 0.00742055, residual=11.0734, model=3.71673e-05
2019-10-02 13:16:40.394 INFO     CG 1: curv=7.33662E-05, converged inside trust region; radius = 0.822578, residual=9.11407e-14, model=0.00307438
2019-10-02 13:16:40.395 INFO     TR 3: obj=0.994053; rho=1.07693
2019-10-02 13:16:40.396 

[ 1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 2  4  5  8 11 15 16  0  1  3  6  7  9 10 12 13 14]
[0. 0.]
[ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0  2  3  6  9  1  4  5  7  8 10 11 12]
[0. 0.]
[ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 3  6  9 10 12  0  1  2  4  5  7  8 11]
[0. 0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1.]
[ 0  1  6 10 12 13 14 16 17 18 20 22 23 24  2  3  4  5  7  8  9 11 15 19
 21]
[0. 0.]


array([ 0.05690021, -0.46189702])

array([-0.26721011,  1.48771909])

array([ 0.26720979, -1.71880035])

array([ 0.10852003, -1.26878114])

In [32]:
t.test_BOSARIS()

2019-10-02 12:01:42.798 INFO     CG 0: curv=294.805, radius = 0.0253862, residual=4.09537, model=0.0949948
2019-10-02 12:01:42.799 INFO     CG 1: curv=9.07096, converged inside trust region; radius = 0.0746529, residual=0.537204, model=0.181842
2019-10-02 12:01:42.800 INFO     TR 1: obj=0.778982; rho=1.21544
2019-10-02 12:01:42.801 INFO     CG 0: curv=55.8271, radius = 0.018161, residual=3.53158, model=0.0349026
2019-10-02 12:01:42.803 INFO     CG 1: curv=1.30004, converged inside trust region; radius = 0.0457992, residual=0.771534, model=0.0582168
2019-10-02 12:01:42.804 INFO     TR 2: obj=0.70784; rho=1.22201
2019-10-02 12:01:42.806 INFO     CG 0: curv=3.80428, radius = 0.0100918, residual=4.47283, model=0.00651286
2019-10-02 12:01:42.807 INFO     CG 1: curv=0.128042, radius = 0.0347561, residual=2.18038, model=0.0142579
2019-10-02 12:01:42.808 INFO     CG 2: curv=0.000523244, converged inside trust region; radius = 0.878535, residual=1.55973e-12, model=0.121278
2019-10-02 12:01:42.8

In [39]:
# ----------------synthesize training data -------------------
# randn('state',0);
means = numpy.random.normal(loc=0, scale=1, size=no_of_systems * 2).reshape(no_of_systems, 2) * 8  # signal
tar, non = make_data(N, means)
means
tar
non

array([[ 1.25804382,  1.82411732],
       [12.1705035 , -2.05549264]])

array([[  3.28779501,  -1.14984424,   2.94844011,   5.49636474,
          6.28827087,   7.14643926,   6.33256484,  -2.95505459,
          5.35914169,   5.22317764,  -4.09427745,   3.23632497,
          4.41914892,   0.83789112,  -0.05449719,  -7.28755746,
          4.1314822 ,   5.43869823,   5.89196217,   3.37532999,
         -1.90837059,   5.31165879,  -5.95052757,  11.53115583,
          0.10128646,   3.73599499,   7.33055603,  -2.41709382,
         -3.2908347 ,   3.88997759,   1.97056769,  -0.03519455,
         -5.1849186 ,   1.49012788,   2.58234145,   9.761849  ,
          3.61400235,  -3.92210584,  -2.80749452,   2.37743249,
          0.75603371,   2.26296673,  10.18853564,   2.69405877,
          5.19567004,   5.9332144 ,   3.59386905,   1.10227409,
         -4.22412526,  -3.28899975,  -4.51026334,   2.19087398,
         -5.8731419 ,   4.19971667,  -0.96316377,  -2.53282506,
         -3.08178661,   1.87840818,  -4.20467695,   2.34685496,
          0.75065074,  -5.90427423,   7.

array([[-5.48424179e+00, -1.07741610e+00,  2.32604022e-01,
         3.25142401e+00,  3.43016001e+00, -5.30591792e+00,
         1.53093635e+00, -1.75594043e+00,  9.15591734e+00,
         1.01232130e-01,  2.05046854e+00,  3.32884343e+00,
         6.84832071e+00,  1.00281148e+01,  3.41419322e+00,
         6.02572217e-01, -9.09823187e+00, -2.24256315e-01,
        -3.62802159e+00,  9.20685808e-01,  4.16695050e+00,
        -9.67242360e+00,  2.56630670e+00,  8.96855445e+00,
         8.46051001e+00,  4.54249579e+00,  1.50006554e+01,
        -7.68857070e-02, -6.26330826e-01, -1.18529571e+01,
         3.01484542e+00,  1.37972923e+00, -4.53015841e+00,
        -5.61569024e-01, -6.45712468e-03,  1.06888949e+01,
         4.63510478e+00, -4.06303714e+00,  4.78944278e+00,
         8.50700929e+00, -2.29034258e+00,  2.49100046e+00,
         5.74033211e+00, -1.84230143e+00,  5.22529481e+00,
         3.28247134e+00,  8.54642186e+00, -2.52485645e+00,
        -3.14402854e+00, -2.23128745e+00,  8.97651765e+0

In [43]:
# ------------- create system ------------------------------
train_scores = numpy.vstack((tar.T, non.T)).T
fuser = LinearFuser(scores=train_scores)
train_scores
fuser

array([[ 3.28779501e+00, -1.14984424e+00,  2.94844011e+00,
         5.49636474e+00,  6.28827087e+00,  7.14643926e+00,
         6.33256484e+00, -2.95505459e+00,  5.35914169e+00,
         5.22317764e+00, -4.09427745e+00,  3.23632497e+00,
         4.41914892e+00,  8.37891123e-01, -5.44971938e-02,
        -7.28755746e+00,  4.13148220e+00,  5.43869823e+00,
         5.89196217e+00,  3.37532999e+00, -1.90837059e+00,
         5.31165879e+00, -5.95052757e+00,  1.15311558e+01,
         1.01286456e-01,  3.73599499e+00,  7.33055603e+00,
        -2.41709382e+00, -3.29083470e+00,  3.88997759e+00,
         1.97056769e+00, -3.51945504e-02, -5.18491860e+00,
         1.49012788e+00,  2.58234145e+00,  9.76184900e+00,
         3.61400235e+00, -3.92210584e+00, -2.80749452e+00,
         2.37743249e+00,  7.56033708e-01,  2.26296673e+00,
         1.01885356e+01,  2.69405877e+00,  5.19567004e+00,
         5.93321440e+00,  3.59386905e+00,  1.10227409e+00,
        -4.22412526e+00, -3.28899975e+00, -4.51026334e+0

In [55]:
# ------------- train it ------------------------------
ntar = tar.shape[1]
nnon = non.shape[1]
classf = numpy.hstack((numpy.ones(ntar), -numpy.ones(nnon)))
ntar
nnon
classf

100

100

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1

In [58]:
prior = 0.1
maxiters = 50
quiet = False
objfun = None
w0 = fuser.w
w, train_cxe, w_pen, optimizerState, converged = train_binary_classifier(
    classifier=fuser, classf=classf, w0=w0,
    objective_function=objfun, prior=prior,
    penalizer=None, penalizer_weight=0,
    maxiters=maxiters, maxCG=100, optimizerState=None, quiet=quiet, cstepHessian=True)
w, train_cxe, w_pen, optimizerState, converged

2019-10-02 12:16:31.491 INFO     TR 0 (initial state): obj = 1, Delta = 3.91301
2019-10-02 12:16:31.497 INFO     CG 0: curv=167.778, converged inside trust region; radius = 0.0912617, residual=0.365931, model=0.698684
2019-10-02 12:16:31.500 INFO     TR 1: obj=0.54961; rho=0.644626
2019-10-02 12:16:31.504 INFO     CG 0: curv=10.4151, radius = 0.0351742, residual=2.06065, model=0.0775958
2019-10-02 12:16:31.505 INFO     CG 1: curv=0.174176, radius = 0.0430942, residual=2.14578, model=0.0859621
2019-10-02 12:16:31.507 INFO     CG 2: curv=0.0193479, converged inside trust region; radius = 0.294468, residual=1.00813e-14, model=0.174517
2019-10-02 12:16:31.508 INFO     TR 2: obj=0.359971; rho=1.08665
2019-10-02 12:16:31.510 INFO     CG 0: curv=0.476755, radius = 0.00718432, residual=4.27399, model=0.00333885
2019-10-02 12:16:31.514 INFO     CG 1: curv=0.0436103, radius = 0.0115646, residual=3.24506, model=0.00455682
2019-10-02 12:16:31.515 INFO     CG 2: curv=0.000658717, converged inside t

(array([ 1.08141794e-03,  5.45247904e-01, -3.05589178e+00]),
 0.31205477904881385,
 0,
 {'Delta': 3.9130113088358636,
  'y': 0.31205477904881385,
  'g': array([ 1.81476809e-19, -1.72794721e-19, -1.69406589e-20]),
  'hess': functools.partial(<bound method ReplaceHessian.hessian of <pybosaris.calibration.objectives.ReplaceHessian object at 0x11c732dd8>>, dy=1, w=array([ 1.08141794e-03,  5.45247904e-01, -3.05589178e+00]))},
 True)

In [63]:
train_fuser = LinearFuser(scores=train_scores, w=w)
train_fused_scores = train_fuser.fusion()
train_c = cllr(train_fused_scores[:ntar], train_fused_scores[ntar:])
train_c_min = min_cllr(train_fused_scores[:ntar], train_fused_scores[ntar:])
logging.info('train Cxe = {}, cllr: {}, min: {}'.format(train_cxe, train_c, train_c_min))
train_fuser
train_fused_scores
train_c
train_c_min

2019-10-02 12:18:25.995 INFO     train Cxe = 0.31205477904881385, cllr: 0.2637514171134443, min: 0.21584535551512118


array([  2.09027724,   4.0290762 ,   5.19647912,   4.20116657,
         4.96309286,  -0.0351332 ,   2.03686388,   1.72786071,
         1.35556289,   4.56764213,   2.58550567,   0.31081986,
         2.49519433,   6.52401993,   6.88070452,   1.59195212,
         4.39861387,   4.42511641,   2.07417197,   4.22112704,
         0.68947286,   3.65091918,   5.5919892 ,   6.93280258,
         7.92143683,   0.38075744,  -3.4903191 ,  -0.57494235,
         3.53165098,   4.4704519 ,   3.12324077,   1.43242045,
         3.51263698,   3.17547334,   2.94967878,   7.82493092,
         2.53033004,   5.24288083,  10.78539738,   5.37195944,
         1.51224506,   2.99667563,   2.27213263,   3.66218578,
         4.43979841,   2.82907164,   5.69383011,   4.51037676,
         5.17000764,   2.31955706,   0.79500192,   9.10796654,
         4.73088118,   7.71391059,   6.53138545,   4.86659629,
         7.96015787,   3.00543418,  -0.75532633,  -0.37992289,
         2.0915784 ,   8.99465482,   5.41050492,   5.86

0.2637514171134443

0.21584535551512118